"""empty message

Revision ID: 09e9ad544e47
Revises: 
Create Date: 2020-05-09 14:48:20.445885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e9ad544e47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
